directories:
  output: dist-electron
  buildResources: build
appId: com.shopapp.admin
productName: Shop Admin
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - node_modules/**/*
icon: public/barcode-scanner.png
mac:
  category: public.app-category.business
win:
  target: nsis
  icon: public/barcode-scanner.png
linux:
  target: AppImage
  icon: public/barcode-scanner.png
electronVersion: 32.3.3
